/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import domain.BibliotecarioEntity;
import domain.UsuarioEntity;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author luisp
 */
public class AgregarUsuarioFrm extends javax.swing.JFrame {

    /**
     * Creates new form AgregarUsuarioFRM
     */
    public AgregarUsuarioFrm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCurp = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtFecha = new com.github.lgooddatepicker.components.DatePicker();
        btnAgregarUsuario = new javax.swing.JToggleButton();
        btnCancelar = new javax.swing.JToggleButton();
        txtMatricula = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCurp.setBorder(null);
        txtCurp.setToolTipText("e.g. COPL030607HSRNRSA9");
        getContentPane().add(txtCurp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 160, -1));

        txtNombre.setBorder(null);
        txtNombre.setToolTipText("e.g. Elon Musk");
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 160, -1));

        txtApellido.setBorder(null);
        txtApellido.setToolTipText("e.g. Bezos");
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 160, -1));
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 180, -1));

        btnAgregarUsuario.setBorder(null);
        btnAgregarUsuario.setContentAreaFilled(false);
        btnAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 100, 30));

        btnCancelar.setBorder(null);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 20));

        txtMatricula.setBorder(null);
        txtMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatriculaActionPerformed(evt);
            }
        });
        getContentPane().add(txtMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 160, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AgregarUsuarioFrm.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarUsuarioActionPerformed
        if(validaCamposVacios() == true){
            BibliotecarioEntity usuarioAccess = new BibliotecarioEntity();
            
            DTOAgregarUsuario agregarUsuarioDTO = new DTOAgregarUsuario(txtNombre.getText(), txtApellido.getText(),
                    txtFecha.getDate(), txtCurp.getText(), txtMatricula.getText());
            
            try {
                usuarioAccess.registraUsuario(agregarUsuarioDTO);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(AgregarUsuarioFrm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(AgregarUsuarioFrm.class.getName()).log(Level.SEVERE, null, ex);
            }
           
            
            this.dispose();
            new GestionUsuariosFrm().setVisible(true);
            
        }else{
            JOptionPane.showMessageDialog(null, "Campos vacíos o invalidos, ingrese nuevamente");
        }
    }//GEN-LAST:event_btnAgregarUsuarioActionPerformed

    private void txtMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatriculaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       this.dispose();
       new GestionUsuariosFrm().setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAgregarUsuario;
    private javax.swing.JToggleButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCurp;
    private com.github.lgooddatepicker.components.DatePicker txtFecha;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    private boolean validaCamposVacios(){
        if(txtNombre.getText().isBlank() || txtApellido.getText().isBlank() ||
                txtCurp.getText().isBlank() || txtFecha.getDate() == null){
                return false;
        }
        return true;
    }

}
