/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import domain.BibliotecarioEntity;
import domain.UsuarioEntity;
import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author xfs85
 */
public class EditarUsuarioFrm extends javax.swing.JFrame {

    UsuarioEntity usu;

    /**
     * Creates new form EditarUsuarioFrm
     * @param usuario
     */
    public EditarUsuarioFrm(UsuarioEntity usuario) {
        initComponents();
        this.usu = usuario;
        LocalDate fNac = usu.getFechaNacimiento().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

        txtNombre.setText(usu.getNombre());
        txtApellido.setText(usu.getApellidos());
        txtFecha.setDate(fNac);
        txtCurp.setText(usu.getCurp());
        txtMatricula.setText(usu.getMatricula());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtFecha = new com.github.lgooddatepicker.components.DatePicker();
        txtCurp = new javax.swing.JTextField();
        txtMatricula = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 210, -1));
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 210, -1));
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));
        jPanel1.add(txtCurp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 210, -1));
        jPanel1.add(txtMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 210, -1));

        btnGuardar.setBorder(null);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 100, 40));

        btnVolver.setBorder(null);
        btnVolver.setContentAreaFilled(false);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EditarUsuario.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (validaCamposVacios() == true) {
            BibliotecarioEntity libroAccess = new BibliotecarioEntity();
            DTOAgregarUsuario usuarioDTO = new DTOAgregarUsuario(this.usu.getId(), this.txtNombre.getText(), this.txtApellido.getText(), this.txtFecha.getDate(), this.txtCurp.getText(), this.txtMatricula.getText());
            libroAccess.editaUsuario(usuarioDTO);

            this.dispose();
            new GestionUsuariosFrm().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Campos vacíos o invalidos, ingrese nuevamente");
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
        new GestionUsuariosFrm().setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    private boolean validaCamposVacios() {
        if (txtNombre.getText().isBlank() || txtApellido.getText().isBlank() || txtFecha.getText().isBlank()
                || txtCurp.getText().isBlank() || txtMatricula.getText().isBlank()) {
            return false;
        }
        return true;
    }

    public void mostrarMensaje(String mensaje, String tipo, String titulo) {
        JOptionPane optionPane = new JOptionPane(mensaje);
        if (tipo.equals("Info")) {
            optionPane.setMessageType(JOptionPane.INFORMATION_MESSAGE);
        } else if (tipo.equals("Error")) {
            optionPane.setMessageType(JOptionPane.ERROR_MESSAGE);
        }
        JDialog dialog = optionPane.createDialog(titulo);
        dialog.setAlwaysOnTop(true);
        dialog.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCurp;
    private com.github.lgooddatepicker.components.DatePicker txtFecha;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
