/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import domain.BibliotecarioEntity;
import domain.EstadoLibro;
import domain.LibroEntity;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author xfs85
 */
public class PrestamosFrm extends javax.swing.JFrame {

    /**
     * Creates new form PrestamosFrm
     */
    List<LibroEntity> libros;
    DefaultTableModel tableModelBooks = new DefaultTableModel();
    LibroEntity libroModel = new LibroEntity();

    public PrestamosFrm() {
        initComponents();
       tableModelBooks.addColumn("ID");
        tableModelBooks.addColumn("Titulo");
        tableModelBooks.addColumn("Autor");
        tableModelBooks.addColumn("Estado");

        librosTable.setModel(tableModelBooks);

        TableColumn columnID = librosTable.getColumnModel().getColumn(0);

        columnID.setResizable(false);

        TableColumn columnTitle = librosTable.getColumnModel().getColumn(1);

        columnTitle.setResizable(false);

        TableColumn columnAutor = librosTable.getColumnModel().getColumn(2);

        columnAutor.setResizable(false);

        TableColumn columnEstado = librosTable.getColumnModel().getColumn(3);

        columnEstado.setResizable(false);

        cargarLibros(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        librosTable = new javax.swing.JTable();
        btnPrestar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        librosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(librosTable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 420, 280));

        btnPrestar.setBorder(null);
        btnPrestar.setContentAreaFilled(false);
        btnPrestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestarActionPerformed(evt);
            }
        });
        jPanel2.add(btnPrestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 100, 30));

        btnVolver.setBorder(null);
        btnVolver.setContentAreaFilled(false);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel2.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 13, 40, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PrestamosFrm.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestarActionPerformed
          int selectedRow = librosTable.getSelectedRow();

                if (selectedRow != -1) {
                    BibliotecarioEntity prestamoAccess = new BibliotecarioEntity();
                    DTOAgregarLibro libroAPrestar= new DTOAgregarLibro();
                    
                    libroAPrestar.setId((Long) librosTable.getValueAt(selectedRow, 0));
                    libroAPrestar.setTitulo(String.valueOf(librosTable.getValueAt(selectedRow, 1))); 
                    libroAPrestar.setAutor(String.valueOf(librosTable.getValueAt(selectedRow, 2)));
                    
                    
              try {
                  prestamoAccess.prestarLibro(libroAPrestar);
              } catch (IllegalAccessException ex) {
                  Logger.getLogger(PrestamosFrm.class.getName()).log(Level.SEVERE, null, ex);
              } catch (InstantiationException ex) {
                  Logger.getLogger(PrestamosFrm.class.getName()).log(Level.SEVERE, null, ex);
              }

                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Seleccione un libro");
                }   
                
                this.dispose();
                new GestionPrestamosFrm().setVisible(true);
    }//GEN-LAST:event_btnPrestarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
        new GestionPrestamosFrm().setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void cargarLibros() {
        List<LibroEntity> libros = libroModel.cargarLibrosDisponibles();
        this.libros = libros;
        tableModelBooks.setRowCount(0);

        for (LibroEntity libro : libros) {
            Object[] row = {
                libro.getId(),
                libro.getTitulo(),
                libro.getAutor(),
                libro.getEstado()

            };

            tableModelBooks.addRow(row);

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrestar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable librosTable;
    // End of variables declaration//GEN-END:variables
}
