/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import domain.BibliotecarioEntity;
import domain.LibroEntity;

/**
 *
 * @author waw
 */
public class ValoracionLibroFrm extends javax.swing.JFrame {

    /**
     * Creates new form ValoracionLibroFrm
     */
    
    
    public ValoracionLibroFrm(LibroEntity libro) {
        initComponents();
        this.valoracionGeneralLabel1.setText(String.valueOf(solicitaValoracion(libro)).toString()); 
        this.nombreLibroLabel1.setText(libro.getTitulo());
        System.err.println("");
        
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolver = new javax.swing.JButton();
        nombreLibroLabel1 = new javax.swing.JLabel();
        valoracionGeneralLabel1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolver.setBorder(null);
        btnVolver.setContentAreaFilled(false);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 40, 30));

        nombreLibroLabel1.setBackground(new java.awt.Color(0, 0, 0));
        nombreLibroLabel1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        nombreLibroLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreLibroLabel1.setText("Nombre");
        getContentPane().add(nombreLibroLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 170, -1));

        valoracionGeneralLabel1.setBackground(new java.awt.Color(0, 0, 0));
        valoracionGeneralLabel1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        valoracionGeneralLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valoracionGeneralLabel1.setText("Valoración");
        getContentPane().add(valoracionGeneralLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 170, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ValoracionLibro.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
       this.dispose();
       new GestionLibrosFrm().setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    
    public float solicitaValoracion(LibroEntity libro){
        BibliotecarioEntity bibliotecario = new BibliotecarioEntity();
    
        return bibliotecario.solicitaValoracionLibro(libro);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nombreLibroLabel1;
    private javax.swing.JLabel valoracionGeneralLabel1;
    // End of variables declaration//GEN-END:variables
}
